query<-list()
query$pid="fao_commodity_dbquery_adv"
query$layer="fao_commodities_dbquery_adv_layer"
query$csw_server="https://geonetwork-sdi-lab.d4science.org/geonetwork/srv/eng/csw"
query$csw_version="2.0.2"
query$wfs_server="https://geoserver-sdi-lab.d4science.org/geoserver/sdilab_fisheriesatlas/ows"
query$wfs_version="1.0.0"
query$feature_geom="true"
query$wms_server="https://geoserver-sdi-lab.d4science.org/geoserver/sdilab_fisheriesatlas/wms"
query$wms_version="1.1.0"
query$stratgy="ogc_viewparams"
query$par="trade_flow:E;aggregation_method:sum"
query$x=-61.34765625
query$y=10.50292968750001
query$srs="EPSG:4326"
query$dsd=""
query

#?withFlag=TRUE&flagCol=flag&line.x=year&line.z=commodity&pie.x=commodity&pie.z=year&box.x=commodity&box.z=year&panel=line+pie+box+data&pid=fao_commodity_dbquery_adv&layer=fao_commodities_dbquery_adv_layer&csw_server=https://geonetwork-sdi-lab.d4science.org/geonetwork/srv/eng/csw&csw_version=2.0.2&wfs_server=https://geoserver-sdi-lab.d4science.org/geoserver/sdilab_fisheriesatlas/ows&wfs_version=1.0.0&feature_geom=false&strategy=ogc_viewparams&par=trade_flow:E;aggregation_method:sum&srs=EPSG:4326